[package]
name = "maze"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex_color = { version = "2.0.0", features = ["rand", "std"] }
rand = "0.8.5"
svg = "0.13.1"
vector2d = "2.2.0"
